name = "hasteless"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

kv_namespaces = [
  { binding = "HASTE_POSTS", id = "KV_ID" }
]

[build]
command = "cargo install -q worker-build && worker-build --release"

[triggers]
crons = ["*/30 * * * *"]
